### ISSUE TITLE
自动保存微信公众号图片Bug

### ISSUE THREAD

**Issue by dingli8888** [ihacklog/hacklog-remote-image-autosave#1]
1.通过wordpress创建一个文章，这个内容来自于微信公众号地址（如：https://mp.weixin.qq.com/s?__biz=MjM5MDAwNTk4MA==&mid=402122868&idx=3&sn=453244c1d373eb4a42194e315f29e492&scene=0&key=710a5d99946419d990526840fd40ca9bde3bf2e2a5cfd24b4274d75f3521b04fb80420a20193b72d85c1c3df5cfed22a&ascene=0&uin=MTQwNTc1&devicetype=iMac+MacBookPro12%2C1+OSX+OSX+10.11.3+build(15D21)&version=11020201&pass_ticket=vNQVCz%2BeeLSuhjAdYw0XD99pDnEBs0IHc9IfcdNhuMo%3D）
2.然后再点Hacklog，自动保存图片，然后点击发布后，这次可以。

3.重复上面的仍然选择微信公众号的内容（与第一篇不同），这时，图片仍然是第一次的图片。

**Comment by ihacklog** [comment]
看了下。从上述微信文章url自动下载图片时，前面的图片全部会被最后下载的那张图片覆盖掉。

**Comment by ihacklog** [comment]
fixed #1  tag 2.1.0

**Comment by dingli8888** [comment]
谢谢。
