### ISSUE TITLE
wordpress升级到4.8后插件失效

### ISSUE THREAD

**Issue by sbw983** [ihacklog/hacklog-remote-image-autosave#6]
wordpress更新到4.8后点击hacklog-remote-image-autosave按钮后所有图片显示已经下载，但是文章发布后发现所有远程图片还是原图，没有保存到本地库，希望能修复，谢谢

我的小站建了4年，换了2家空间提供商，但是hacklog-remote-image-autosave一直是我必装的插件，因为他实在很强大，希望能继续更新。辛苦了

**Comment by ihacklog** [comment]
好的，我看看

**Comment by ihacklog** [comment]
WordPress 4.9.5 下测试,使用正常.
